import os
from dotenv import load_dotenv

load_dotenv()

ENVIRONMENT = os.getenv("ENVIRONMENT") if "ENVIRONMENT" in os.environ else "development"
TELEMETRY_KEY = os.getenv("TELEMETRY_KEY")
COSMOS_CONNECTION_STRING = os.getenv("COSMOS_CONNECTION_STRING")
OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL")
OPENAI_GPT4_BASE_URL = os.getenv("OPENAI_GPT4_BASE_URL")
OPENAI_GPT4_API_KEY = os.getenv("OPENAI_GPT4_API_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
DEFAULT_KEY_DATABASE_NAME = "api"
DEFAULT_KEY_CONTAINER_NAME = "keys"
DEFAULT_ACCOUNT_CONTAINER_NAME = "accounts"
ADF_SP_SECRET = os.getenv("ADF_SP_SECRET")
ADF_SP_CLIENT_ID = os.getenv("ADF_SP_CLIENT_ID")
ADF_SP_TENANT_ID = os.getenv("ADF_SP_TENANT_ID")
ADF_SP_SUBSCRIPTION_ID = os.getenv("ADF_SP_SUBSCRIPTION_ID")
SEARCH_ENDPOINT = os.getenv("SEARCH_ENDPOINT")
SEARCH_KEY = os.getenv("SEARCH_KEY")
AI_STUDIO_BASE_URL = os.getenv("AI_STUDIO_BASE_URL")
META_LLAMA2_CHAT_API_KEY = os.getenv("META_LLAMA2_CHAT_API_KEY")
MISTRAL_LARGE_CHAT_API_KEY = os.getenv("MISTRAL_LARGE_CHAT_API_KEY")
AZURE_SERVICE_BUS_CONNECTION_STRING = os.getenv("AZURE_SERVICE_BUS_CONNECTION_STRING")
AZURE_SIGNALR_CONNECTION_STRING = os.getenv("AZURE_SIGNALR_CONNECTION_STRING")
SERVICE_BASE_URL= os.getenv("SERVICE_BASE_URL")

#Azure ML Studio Models
CATEGORIZE_QUERY_MODEL_API_KEY = os.getenv("CATEGORIZE_QUERY_MODEL_API_KEY")