import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_3f13f19bf4(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_666cbae6d0():spartaqube_cli.list()
@app.command()
def sparta_9eda191ef0():spartaqube_cli.sparta_9eda191ef0()
@app.command()
def sparta_832baf3aa9():print('Hello world!')
if __name__=='__main__':app()