import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_301bd4dfcc(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_5b8c2caf18():spartaqube_cli.list()
@app.command()
def sparta_117f8101e3():spartaqube_cli.sparta_117f8101e3()
@app.command()
def sparta_35d25e7e83():print('Hello world!')
if __name__=='__main__':app()