__app_name__ = "JacksonBorbon-LinkChecker"
__version__ = "10.4.0.post36"
__release_date__ = "2024-08-21"
__copyright_year__ = "2024"
__author__ = "LinkChecker Authors"
__url__ = "https://linkchecker.github.io/linkchecker/"
__support_url__ = "https://github.com/linkchecker/linkchecker/issues"
