from _typeshed import Incomplete

from google.auth.crypt import base as base

class ES256Verifier(base.Verifier):
    def __init__(self, public_key) -> None: ...
    def verify(self, message, signature): ...
    @classmethod
    def from_string(cls, public_key): ...

class ES256Signer(base.Signer, base.FromServiceAccountMixin):
    def __init__(self, private_key, key_id: Incomplete | None = ...) -> None: ...
    @property
    def key_id(self): ...
    def sign(self, message): ...
    @classmethod
    def from_string(cls, key, key_id: Incomplete | None = ...): ...
