MIN_ANGLE_DEGR_VALUE = 1e-6
MIN_ANGLE_DEGR_DISORIENTATION = 5.
VECTOR_ANGLE_THRESHOLD = 1
PLANE_ANGLE_THRESHOLD = 1
DIP_ANGLE_THRESHOLD = 5
DIP_ROTAT_ANGLE_THRESH = 2.5  # dipang rot_angle threshold, degrees
RAKE_THRESHOLD = 5.0  # rake, degrees