#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2404-50-g0fb5b416"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2404
#define NETGEN_VERSION_TWEAK 50
#define NETGEN_VERSION_HASH "g0fb5b416"
#endif // NETGEN_VERSION_HPP_INCLUDED
