
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-27T06:57:31+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3266395f249f4e6baa4c660486f8d9c3bbcc3b36",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
