from _typeshed import Incomplete

REFRESH_THRESHOLD: Incomplete

def copy_docstring(source_class): ...
def utcnow(): ...
def datetime_to_secs(value): ...
def to_bytes(value, encoding: str = ...): ...
def from_bytes(value): ...
def update_query(url, params, remove: Incomplete | None = ...): ...
def scopes_to_string(scopes): ...
def string_to_scopes(scopes): ...
def padded_urlsafe_b64decode(value): ...
def unpadded_urlsafe_b64encode(value): ...
def is_python_3(): ...
