from _typeshed import Incomplete

class GoogleAuthError(Exception): ...
class TransportError(GoogleAuthError): ...
class RefreshError(GoogleAuthError): ...
class UserAccessTokenError(GoogleAuthError): ...
class DefaultCredentialsError(GoogleAuthError): ...
class MutualTLSChannelError(GoogleAuthError): ...
class ClientCertError(GoogleAuthError): ...
class OAuthError(GoogleAuthError): ...

class ReauthFailError(RefreshError):
    def __init__(self, message: Incomplete | None = ...) -> None: ...

class ReauthSamlChallengeFailError(ReauthFailError): ...
