from google.auth import crypt as crypt, exceptions as exceptions

class Signer(crypt.Signer):
    def __init__(self, request, credentials, service_account_email) -> None: ...
    @property
    def key_id(self) -> None: ...
    def sign(self, message): ...
