WORKFLOW_PAYLOAD = {
    "type": "taskWorkflow",
    "actions": {
        "abortActions": [],
        "emailNotifications": [],
        "setVariableActions": [],
        "snmpNotifications": [],
        "systemOperations": []
    },
    "calculateCp": False,
    "calendar": None,
    "cpDuration": None,
    "cpDurationUnit": "Minutes",
    "criticalEndpoints": [],
    "customField1": {
        "label": "Documentation",
        "value": None
    },
    "customField2": {
        "label": "Ticket Number",
        "value": None
    },
    "efDayConstraint": "None",
    "efDuration": "00:00:00:00",
    "efEnabled": False,
    "efNthAmount": 5,
    "efOffsetDuration": None,
    "efOffsetDurationUnit": "Minutes",
    "efOffsetPercentage": 0,
    "efOffsetType": "Percentage",
    "efTime": "00:00",
    "efType": "Time",
    "enforceVariables": False,
    "exclusiveTasks": [],
    "exclusiveWithSelf": False,
    "executionRestriction": "None",
    "exportReleaseLevel": "7.6.0.1",
    "exportTable": "ops_task_workflow",
    "firstRun": "",
    "holdResources": False,
    "instanceWait": "-- None --",
    "lastRun": "",
    "layoutOption": "-- None --",
    "lfDayConstraint": "None",
    "lfDuration": "00:00:00:00",
    "lfEnabled": False,
    "lfNthAmount": 5,
    "lfOffsetDuration": None,
    "lfOffsetDurationUnit": "Minutes",
    "lfOffsetPercentage": 0,
    "lfOffsetType": "Percentage",
    "lfTime": "00:00",
    "lfType": "Time",
    "lockVariables": False,
    "logLevel": "Inherited",
    "lsDayConstraint": "None",
    "lsDuration": "00:00:00:00",
    "lsEnabled": False,
    "lsNthAmount": 5,
    "lsTime": "00:00",
    "lsType": "Time",
    "notes": [],
    "numberOfTasks": None,
    "opswiseGroups": [],
    "overrideCalendar": False,
    "overrideInstanceWait": "No",
    "resPriority": 10,
    "resolveNameImmediately": False,
    "restrictionPeriod": "None",
    "restrictionPeriodAfterDate": None,
    "restrictionPeriodAfterTime": None,
    "restrictionPeriodBeforeDate": None,
    "restrictionPeriodBeforeTime": None,
    "restrictionPeriodDateList": [],
    "retainSysIds": True,
    "runCount": 0,
    "runCriteria": [],
    "runTime": 0,
    "simulation": False,
    "skippedOption": "Show Skipped",
    "startHeld": False,
    "startHeldReason": None,
    "stepActions": [],
    "stepConditions": [],
    "summary": None,
    "timeZonePref": "-- System Default --",
    "twDelayAmount": None,
    "twDelayDuration": "00:00:00:00",
    "twDelayType": "None",
    "twWaitAmount": None,
    "twWaitDayConstraint": "None",
    "twWaitDuration": "00:00:00:00",
    "twWaitTime": "00:00",
    "twWaitType": "None",
    "twWorkflowOnly": "-- System Default --",
    "userEstimatedDuration": None,
    "variables": [],
    "version": 1,
    "virtualResources": [],
    "workflowEdges": [],
    "workflowVertices": []
}

VARIABLE_PAYLOAD = {
    "allowEmptyOption" : False,
    "allowUnlistedOption" : False,
    "description" : None,
    "name" : "",
    "options" : [ ],
    "value" : ""
  }

SQL_TASK_SET_VARIABLE_ACTION_PAYLOAD = {
      "description" : None,
      "exitCodes" : None,
      "notificationOption" : "Operation Failure",
      "notifyOnEarlyFinish" : False,
      "notifyOnLateFinish" : False,
      "notifyOnLateStart" : False,
      "notifyOnProjectedLate" : False,
      "status" : "Success",
      "variableName" : "",
      "variableScope" : "Global",
      "variableValue" : "${_resultsColumnByNo('',1,1)}"
    }

LINUX_TASK_PAYLOAD = {
    "type": "taskUnix",
    "actions": {
        "abortActions": [],
        "emailNotifications": [],
        "setVariableActions": [],
        "snmpNotifications": [],
        "systemOperations": []
    },
    "agent": None,
    "agentCluster": None,
    "agentClusterVar": None,
    "agentVar": "{VAR_AGENT}",
    "broadcastCluster": None,
    "broadcastClusterVar": None,
    "command": "{COMMAND}",
    "commandOrScript": "Command",
    "cpDuration": None,
    "cpDurationUnit": "Minutes",
    "credentials": None,
    "credentialsVar": None,
    "customField1": {
        "label": "Documentation",
        "value": None
    },
    "customField2": {
        "label": "Ticket Number",
        "value": None
    },
    "efDayConstraint": "None",
    "efDuration": "00:00:00:00",
    "efEnabled": False,
    "efNthAmount": 5,
    "efOffsetDuration": None,
    "efOffsetDurationUnit": "Minutes",
    "efOffsetPercentage": 0,
    "efOffsetType": "Percentage",
    "efTime": "00:00",
    "efType": "Time",
    "enforceVariables": False,
    "environment": [],
    "exclusiveTasks": [],
    "exclusiveWithSelf": False,
    "executionRestriction": "None",
    "exitCodeOutput": None,
    "exitCodeProcessing": "Success Exitcode Range",
    "exitCodeText": None,
    "exitCodes": "0",
    "exportReleaseLevel": "7.6.0.1",
    "exportTable": "ops_task_unix",
    "firstRun": "",
    "holdResources": False,
    "lastRun": "",
    "lfDayConstraint": "None",
    "lfDuration": "00:00:00:00",
    "lfEnabled": False,
    "lfNthAmount": 5,
    "lfOffsetDuration": None,
    "lfOffsetDurationUnit": "Minutes",
    "lfOffsetPercentage": 0,
    "lfOffsetType": "Percentage",
    "lfTime": "00:00",
    "lfType": "Time",
    "lockVariables": False,
    "logLevel": "Inherited",
    "lsDayConstraint": "None",
    "lsDuration": "00:00:00:00",
    "lsEnabled": False,
    "lsNthAmount": 5,
    "lsTime": "00:00",
    "lsType": "Time",
    "notes": [],
    "opswiseGroups": [],
    "outputFailureOnly": False,
    "outputReturnFile": None,
    "outputReturnNline": "100",
    "outputReturnSline": "1",
    "outputReturnText": None,
    "outputReturnType": "NONE",
    "outputType": "STDOUT",
    "overrideInstanceWait": "No",
    "parameters": None,
    "resPriority": 10,
    "resolveNameImmediately": False,
    "restrictionPeriod": "None",
    "restrictionPeriodAfterDate": None,
    "restrictionPeriodAfterTime": None,
    "restrictionPeriodBeforeDate": None,
    "restrictionPeriodBeforeTime": None,
    "restrictionPeriodDateList": [],
    "retainSysIds": True,
    "retryExitCodes": None,
    "retryIndefinitely": False,
    "retryInterval": 60,
    "retryMaximum": 0,
    "retrySuppressFailure": False,
    "runAsSudo": False,
    "runCount": 0,
    "runTime": 0,
    "runtimeDir": None,
    "script": None,
    "simulation": False,
    "startHeld": False,
    "startHeldReason": None,
    "summary": None,
    "timeZonePref": "-- System Default --",
    "twDelayAmount": None,
    "twDelayDuration": "00:00:00:00",
    "twDelayType": "None",
    "twWaitAmount": None,
    "twWaitDayConstraint": "None",
    "twWaitDuration": "00:00:00:00",
    "twWaitTime": "00:00",
    "twWaitType": "None",
    "twWorkflowOnly": "-- System Default --",
    "userEstimatedDuration": None,
    "variables": [],
    "version": 1,
    "virtualResources": [],
    "waitForOutput": False
}

WINDOWS_TASK_PAYLOAD = {
    "type": "taskWindows",
    "actions": {
        "abortActions": [],
        "emailNotifications": [],
        "setVariableActions": [],
        "snmpNotifications": [],
        "systemOperations": []
    },
    "agent": None,
    "agentCluster": None,
    "agentClusterVar": None,
    "agentVar": "{AGENT}",
    "broadcastCluster": None,
    "broadcastClusterVar": None,
    "command": "{COMMAND}",
    "commandOrScript": "Command",
    "cpDuration": None,
    "cpDurationUnit": "Minutes",
    "createConsole": False,
    "credentials": None,
    "credentialsVar": None,
    "customField1": {
        "label": "Documentation",
        "value": None
    },
    "customField2": {
        "label": "Ticket Number",
        "value": None
    },
    "desktopInteract": False,
    "efDayConstraint": "None",
    "efDuration": "00:00:00:00",
    "efEnabled": False,
    "efNthAmount": 5,
    "efOffsetDuration": None,
    "efOffsetDurationUnit": "Minutes",
    "efOffsetPercentage": 0,
    "efOffsetType": "Percentage",
    "efTime": "00:00",
    "efType": "Time",
    "elevateUser": False,
    "enforceVariables": False,
    "environment": [],
    "exclusiveTasks": [],
    "exclusiveWithSelf": False,
    "executionRestriction": "None",
    "exitCodeOutput": None,
    "exitCodeProcessing": "Success Exitcode Range",
    "exitCodeText": None,
    "exitCodes": "0",
    "exportReleaseLevel": "7.6.0.1",
    "exportTable": "ops_task_windows",
    "firstRun": "",
    "holdResources": False,
    "lastRun": "",
    "lfDayConstraint": "None",
    "lfDuration": "00:00:00:00",
    "lfEnabled": False,
    "lfNthAmount": 5,
    "lfOffsetDuration": None,
    "lfOffsetDurationUnit": "Minutes",
    "lfOffsetPercentage": 0,
    "lfOffsetType": "Percentage",
    "lfTime": "00:00",
    "lfType": "Time",
    "lockVariables": False,
    "logLevel": "Inherited",
    "lsDayConstraint": "None",
    "lsDuration": "00:00:00:00",
    "lsEnabled": False,
    "lsNthAmount": 5,
    "lsTime": "00:00",
    "lsType": "Time",
    "notes": [],
    "opswiseGroups": [],
    "outputFailureOnly": False,
    "outputReturnFile": None,
    "outputReturnNline": "100",
    "outputReturnSline": "1",
    "outputReturnText": None,
    "outputReturnType": "NONE",
    "outputType": "STDOUT",
    "overrideInstanceWait": "No",
    "parameters": None,
    "resPriority": 10,
    "resolveNameImmediately": False,
    "restrictionPeriod": "None",
    "restrictionPeriodAfterDate": None,
    "restrictionPeriodAfterTime": None,
    "restrictionPeriodBeforeDate": None,
    "restrictionPeriodBeforeTime": None,
    "restrictionPeriodDateList": [],
    "retainSysIds": True,
    "retryExitCodes": None,
    "retryIndefinitely": False,
    "retryInterval": 60,
    "retryMaximum": 0,
    "retrySuppressFailure": False,
    "runCount": 0,
    "runTime": 0,
    "runtimeDir": None,
    "script": None,
    "simulation": False,
    "startHeld": False,
    "startHeldReason": None,
    "summary": None,
    "timeZonePref": "-- System Default --",
    "twDelayAmount": None,
    "twDelayDuration": "00:00:00:00",
    "twDelayType": "None",
    "twWaitAmount": None,
    "twWaitDayConstraint": "None",
    "twWaitDuration": "00:00:00:00",
    "twWaitTime": "00:00",
    "twWaitType": "None",
    "twWorkflowOnly": "-- System Default --",
    "userEstimatedDuration": None,
    "variables": [],
    "version": 1,
    "virtualResources": [],
    "waitForOutput": False
}

FTP_TASK_PAYLOAD = {
    "type": "taskFtp",
    "actions": {
        "abortActions": [],
        "emailNotifications": [],
        "setVariableActions": [],
        "snmpNotifications": [],
        "systemOperations": []
    },
    "agent": None,
    "agentCluster": None,
    "agentClusterVar": None,
    "agentVar": "${AGENT}",
    "authenticatePeer": False,
    "broadcastCluster": None,
    "broadcastClusterVar": None,
    "codepage": "-- None --",
    "command": "GET",
    "compress": "NO",
    "cpDuration": None,
    "cpDurationUnit": "Minutes",
    "createop": "-- None --",
    "credentials": None,
    "credentialsVar": None,
    "customField1": {
        "label": None,
        "value": None
    },
    "customField2": {
        "label": None,
        "value": None
    },
    "efDayConstraint": "None",
    "efDuration": "00:00:00:00",
    "efEnabled": False,
    "efNthAmount": 5,
    "efOffsetDuration": None,
    "efOffsetDurationUnit": "Minutes",
    "efOffsetPercentage": 0,
    "efOffsetType": "Percentage",
    "efTime": "00:00",
    "efType": "Time",
    "encrypt": "NO",
    "enforceVariables": False,
    "exclusiveTasks": [],
    "exclusiveWithSelf": False,
    "executionRestriction": "None",
    "exitCodeOutput": None,
    "exitCodeProcessing": "Success Exitcode Range",
    "exitCodeText": None,
    "exitCodes": "0",
    "exportReleaseLevel": "7.6.0.1",
    "exportTable": "ops_task_ftp",
    "firstRun": "",
    "formOrScript": "Form",
    "format": "Binary",
    "ftpSubcommands": None,
    "holdResources": False,
    "jobcard": None,
    "lastRun": "",
    "lfDayConstraint": "None",
    "lfDuration": "00:00:00:00",
    "lfEnabled": False,
    "lfNthAmount": 5,
    "lfOffsetDuration": None,
    "lfOffsetDurationUnit": "Minutes",
    "lfOffsetPercentage": 0,
    "lfOffsetType": "Percentage",
    "lfTime": "00:00",
    "lfType": "Time",
    "localFilename": "{LOCAL_FILE}",
    "lockVariables": False,
    "logLevel": "Inherited",
    "lsDayConstraint": "None",
    "lsDuration": "00:00:00:00",
    "lsEnabled": False,
    "lsNthAmount": 5,
    "lsTime": "00:00",
    "lsType": "Time",
    "move": False,
    "nft": False,
    "notes": [],
    "opswiseGroups": [],
    "outputType": "STDOUT",
    "overrideInstanceWait": "No",
    "primaryBroker": None,
    "primaryBrokerChoice": "Agent",
    "primaryBrokerRef": None,
    "primaryCluster": None,
    "primaryClusterRef": None,
    "primaryCredVar": None,
    "primaryCredentials": None,
    "primaryFilesys": "-- None --",
    "primaryOpenOptions": None,
    "remoteCredVar": "{CREDENTIAL}",
    "remoteCredentials": None,
    "remoteFilename": "{REMOTE_FILE}",
    "remoteServer": "{SERVER}",
    "resPriority": 10,
    "resolveNameImmediately": False,
    "restrictionPeriod": "None",
    "restrictionPeriodAfterDate": None,
    "restrictionPeriodAfterTime": None,
    "restrictionPeriodBeforeDate": None,
    "restrictionPeriodBeforeTime": None,
    "restrictionPeriodDateList": [],
    "retainSysIds": True,
    "retryExitCodes": None,
    "retryIndefinitely": False,
    "retryInterval": 60,
    "retryMaximum": 0,
    "retrySuppressFailure": False,
    "runCount": 0,
    "runTime": 0,
    "runtimeDir": None,
    "script": None,
    "secondaryBroker": None,
    "secondaryBrokerChoice": "Agent",
    "secondaryBrokerRef": None,
    "secondaryCluster": None,
    "secondaryClusterRef": None,
    "secondaryCredVar": None,
    "secondaryCredentials": None,
    "secondaryFilesys": "-- None --",
    "secondaryOpenOptions": None,
    "serverType": "SFTP",
    "showProgress": False,
    "simulation": False,
    "startHeld": False,
    "startHeldReason": None,
    "summary": None,
    "timeZonePref": "-- System Default --",
    "transferDirection": "PUT",
    "transferMode": "Passive",
    "trimSpace": False,
    "twDelayAmount": None,
    "twDelayDuration": "00:00:00:00",
    "twDelayType": "None",
    "twWaitAmount": None,
    "twWaitDayConstraint": "None",
    "twWaitDuration": "00:00:00:00",
    "twWaitTime": "00:00",
    "twWaitType": "None",
    "twWorkflowOnly": "-- System Default --",
    "udmOperation": "Copy",
    "udmOptions": None,
    "useRegex": False,
    "userEstimatedDuration": None,
    "variables": [],
    "verifyHostName": False,
    "version": 1,
    "virtualResources": []
}