key = """-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIG+fh6JmrYT4APzbyZA4dBFTMetV8If6CPIBLX2r3xKCoAoGCCqGSM49
AwEHoUQDQgAEYDQpvroqIfE/xOFUA4/Uq0d+uswZ2ZPUwBsAm3A+3ngxxmP9CelC
EUbDIAiVeB9Wm50I0/whycjX2mnFaC7Mdg==
-----END EC PRIVATE KEY-----
"""

cert = """-----BEGIN CERTIFICATE-----
MIIB6jCCAY8CFHPp+B6fMNoYMPndra8GK15qSGPLMAoGCCqGSM49BAMCMHcxCzAJ
BgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UE
CgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25hbCBVbml0MRQw
EgYDVQQDDAtDb21tb24gTmFtZTAeFw0yNDA4MjYwNTU0MTVaFw0zNDA4MjQwNTU0
MTVaMHcxCzAJBgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0
eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25h
bCBVbml0MRQwEgYDVQQDDAtDb21tb24gTmFtZTBZMBMGByqGSM49AgEGCCqGSM49
AwEHA0IABGA0Kb66KiHxP8ThVAOP1KtHfrrMGdmT1MAbAJtwPt54McZj/QnpQhFG
wyAIlXgfVpudCNP8IcnI19ppxWguzHYwCgYIKoZIzj0EAwIDSQAwRgIhAJ81NAOl
rMoXFq0pNPCCclf6twWLTni8+2RUNML9nK4LAiEA9UV2O/6Dp5LB4Xk9ThtfiWYn
pDIetuIptiHPsyjQae0=
-----END CERTIFICATE-----
"""