from _typeshed import Incomplete

from google.auth import exceptions as exceptions

CONTEXT_AWARE_METADATA_PATH: str

def get_client_ssl_credentials(
    generate_encrypted_key: bool = ..., context_aware_metadata_path=...
): ...
def get_client_cert_and_key(client_cert_callback: Incomplete | None = ...): ...
def decrypt_private_key(key, passphrase): ...
