"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import messages.robot_control_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class SubscribeRequest(google.protobuf.message.Message):
    """/ Request message to subscribe to robot data for a robot dataset"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROBOT_DATA_SET_ID_FIELD_NUMBER: builtins.int
    robot_data_set_id: builtins.int
    """/ Robot dataset id of the robot to subscribe to"""
    def __init__(
        self,
        *,
        robot_data_set_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["robot_data_set_id", b"robot_data_set_id"]) -> None: ...

global___SubscribeRequest = SubscribeRequest

@typing_extensions.final
class ControlRequest(google.protobuf.message.Message):
    """/ Request message to send a control command to a robot"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROBOT_DATA_SET_ID_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    robot_data_set_id: builtins.int
    """/ Robot dataset id of the robot to send the command to"""
    @property
    def command(self) -> messages.robot_control_pb2.UserControlCommand:
        """/ Control command to send to the robot"""
    def __init__(
        self,
        *,
        robot_data_set_id: builtins.int = ...,
        command: messages.robot_control_pb2.UserControlCommand | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["command", b"command"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["command", b"command", "robot_data_set_id", b"robot_data_set_id"]) -> None: ...

global___ControlRequest = ControlRequest
