
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-26T06:28:39+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "666150d6450378c94de0017da1d1e2c4ec8ba85f",
 "version": "0.2.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
