# Generated by Django 5.0.6 on 2024-06-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_media_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='compact',
            field=models.ImageField(null=True, upload_to='media/images/compacts'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='media/images/thumbnails'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='media/images/originals'),
        ),
    ]
