
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-28T10:48:02+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1735a993e9dcc16626cfd0c33dfbcf1032735119",
 "version": "0.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
