import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_212ca31061(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_56dd91a793():spartaqube_cli.list()
@app.command()
def sparta_a1672ff818():spartaqube_cli.sparta_a1672ff818()
@app.command()
def sparta_d5513887c6():print('Hello world!')
if __name__=='__main__':app()