
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-08-23T17:26:30+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "06e42fc04778ffa4a4f70ce9683936eb60f13d55",
 "version": "1.14.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
